@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Orders System - Containers

Person(customer, "Customer", "Пользователь")

System_Boundary(s1, "Orders System") {
  Container(web, "Web UI", "React SPA", "Frontend")
  Container(api, "Core API", "Spring Boot", "REST API +. Business Logic")

  ContainerDb(db, "PostgreSQL", "DB", "Database with data")
  ContainerDb(cache, "Redis", "Cache", "Cache, deduplication")
}

System_Ext(paymentProvider, "Payment Provider", "Payment provider")

Rel(customer, web, "Browser", "HTTPS")
Rel(web, api, "REST API", "HTTPS")
Rel(api, db, "CRUD", "JDBC")
Rel(api, cache, "Cache-Aside", "Spring Data Redis")
Rel(api, paymentProvider, "Creating the payment", "HTTPS")

@enduml